# Generated by Django 4.2.15 on 2026-04-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0035_update_trace_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodflagResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifier')),
                ('description', models.TextField(verbose_name='Description')),
                ('base_url', models.URLField(
                    help_text="URL de base de l'API Goodflag Workflow Manager, ex: https://sgs-demo-test01.sunnystamp.com/api",
                    max_length=512,
                    verbose_name="URL de base de l'API Goodflag",
                )),
                ('access_token', models.CharField(
                    help_text="Bearer token pour l'authentification API Goodflag (format: act_xxx.yyy)",
                    max_length=512,
                    verbose_name="Token d'accès API",
                )),
                ('user_id', models.CharField(
                    help_text="Identifiant de l'utilisateur Goodflag propriétaire des workflows créés (format: usr_xxx). Requis pour la création de workflows.",
                    max_length=256,
                    verbose_name='Identifiant utilisateur API',
                )),
                ('timeout', models.PositiveIntegerField(
                    default=30,
                    help_text='Timeout en secondes pour les appels API Goodflag',
                    verbose_name='Timeout HTTP (secondes)',
                )),
                ('verify_ssl', models.BooleanField(
                    default=True,
                    help_text="Activer la vérification SSL. Ne désactiver qu'en environnement de test explicitement.",
                    verbose_name='Vérifier le certificat SSL',
                )),
                ('default_consent_page_id', models.CharField(
                    blank=True,
                    default='',
                    help_text="Identifiant de la page de consentement Goodflag par défaut (format: cop_xxx). Utilisé pour les destinataires qui n'en spécifient pas.",
                    max_length=256,
                    verbose_name='ID de page de consentement par défaut',
                )),
                ('default_signature_profile_id', models.CharField(
                    blank=True,
                    default='',
                    help_text='Identifiant du profil de signature Goodflag par défaut (format: sip_xxx). Utilisé pour les documents à signer.',
                    max_length=256,
                    verbose_name='ID de profil de signature par défaut',
                )),
                ('default_layout_id', models.CharField(
                    blank=True,
                    default='',
                    help_text='Identifiant du layout Goodflag par défaut (format: lay_xxx). Requis si vous utilisez des métadonnées.',
                    max_length=256,
                    verbose_name='ID de layout par défaut',
                )),
                ('webhook_secret', models.CharField(
                    blank=True,
                    default='',
                    help_text="Secret partagé pour valider les webhooks Goodflag. Note : Goodflag ne signe pas ses webhooks par HMAC. Ce champ est utilisé comme token dans l'URL du webhook ou comme header personnalisé pour la validation.",
                    max_length=256,
                    verbose_name='Secret du webhook',
                )),
                ('tenant_id', models.CharField(
                    blank=True,
                    default='',
                    help_text='Identifiant du tenant Goodflag (format: ten_xxx). Utilisé pour les webhooks globaux.',
                    max_length=256,
                    verbose_name='Identifiant du tenant',
                )),
                ('debug_mode', models.BooleanField(
                    default=False,
                    help_text='Active la journalisation détaillée des appels API',
                    verbose_name='Mode debug métier',
                )),
                ('sandbox_mode', models.BooleanField(
                    default=False,
                    help_text='Indique que le connecteur pointe vers un environnement de test',
                    verbose_name='Mode sandbox',
                )),
                ('retention_days', models.PositiveIntegerField(
                    default=90,
                    help_text=(
                        'Durée de conservation des traces de workflows, événements webhook '
                        'et documents avant purge automatique (tâche daily). Défaut : 90 jours.'
                    ),
                    verbose_name='Rétention des traces (jours)',
                )),
                ('publik_callback_url', models.URLField(
                    blank=True,
                    default='',
                    help_text=(
                        "URL de callback Publik/WCS à notifier lors d'un événement webhook "
                        "Goodflag (workflowFinished, workflowStopped). Laisser vide pour "
                        'désactiver. Format: https://wcs.example.com/api/wf/... '
                    ),
                    max_length=512,
                    verbose_name='URL de callback Publik',
                )),
                ('status_cache_ttl', models.PositiveIntegerField(
                    default=120,
                    help_text=(
                        "Durée en secondes pendant laquelle le statut d'un workflow est mis "
                        'en cache pour éviter des appels API répétitifs. 0 = désactivé. '
                        'Défaut : 120 secondes (2 minutes).'
                    ),
                    verbose_name='Durée du cache statut (secondes)',
                )),
                ('users', models.ManyToManyField(
                    blank=True,
                    related_name='+',
                    related_query_name='+',
                    to='base.apiuser',
                )),
            ],
            options={
                'verbose_name': 'Connecteur Goodflag (signature électronique)',
                'verbose_name_plural': 'Connecteurs Goodflag (signature électronique)',
            },
        ),
        migrations.CreateModel(
            name='GoodflagWorkflowTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodflag_workflow_id', models.CharField(db_index=True, max_length=256, verbose_name='ID workflow Goodflag')),
                ('external_ref', models.CharField(
                    blank=True,
                    db_index=True,
                    default='',
                    help_text='Numéro de demande, identifiant usager, etc.',
                    max_length=512,
                    verbose_name='Référence externe Publik',
                )),
                ('workflow_name', models.CharField(blank=True, default='', max_length=512, verbose_name='Nom du workflow')),
                ('status', models.CharField(blank=True, default='draft', max_length=64, verbose_name='Statut courant')),
                ('metadata_json', models.TextField(blank=True, default='{}', verbose_name='Métadonnées (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('resource', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='workflow_traces',
                    to='passerelle_goodflag.goodflagresource',
                    verbose_name='Connecteur',
                )),
            ],
            options={
                'verbose_name': 'Trace workflow Goodflag',
                'verbose_name_plural': 'Traces workflow Goodflag',
                'indexes': [models.Index(fields=['resource', 'external_ref'], name='gf_wf_resource_extref_idx')],
                'unique_together': {('resource', 'goodflag_workflow_id')},
            },
        ),
        migrations.CreateModel(
            name='GoodflagWebhookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(
                    blank=True,
                    db_index=True,
                    default='',
                    help_text='Format: wbe_xxx',
                    max_length=256,
                    verbose_name='ID événement Goodflag',
                )),
                ('event_type', models.CharField(
                    blank=True,
                    default='',
                    help_text='Ex: workflowStarted, workflowFinished, workflowStopped, recipientFinished, recipientRefused, commentCreated',
                    max_length=128,
                    verbose_name="Type d'événement",
                )),
                ('goodflag_workflow_id', models.CharField(
                    blank=True,
                    db_index=True,
                    default='',
                    max_length=256,
                    verbose_name='ID workflow Goodflag',
                )),
                ('webhook_id', models.CharField(
                    blank=True,
                    default='',
                    help_text='Format: wbh_xxx',
                    max_length=256,
                    verbose_name='ID webhook Goodflag',
                )),
                ('step_id', models.CharField(
                    blank=True,
                    default='',
                    help_text='Format: stp_xxx',
                    max_length=256,
                    verbose_name='ID étape Goodflag',
                )),
                ('raw_status', models.CharField(blank=True, default='', max_length=64, verbose_name='Statut brut Goodflag')),
                ('normalized_status', models.CharField(blank=True, default='', max_length=32, verbose_name='Statut normalisé')),
                ('payload_json', models.TextField(blank=True, default='{}', verbose_name='Payload JSON complet')),
                ('timestamp_goodflag', models.CharField(blank=True, default='', max_length=64, verbose_name='Timestamp Goodflag')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception')),
                ('resource', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='webhook_events',
                    to='passerelle_goodflag.goodflagresource',
                    verbose_name='Connecteur',
                )),
            ],
            options={
                'verbose_name': 'Événement webhook Goodflag',
                'verbose_name_plural': 'Événements webhook Goodflag',
                'indexes': [
                    models.Index(fields=['resource', 'event_id'], name='gf_webhook_resource_evtid_idx'),
                    models.Index(fields=['resource', 'goodflag_workflow_id'], name='gf_webhook_resource_wfid_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='GoodflagDocumentTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodflag_workflow_id', models.CharField(db_index=True, max_length=256, verbose_name='ID workflow Goodflag')),
                ('goodflag_document_id', models.CharField(
                    blank=True,
                    default='',
                    help_text='Format: doc_xxx',
                    max_length=256,
                    verbose_name='ID document Goodflag',
                )),
                ('filename', models.CharField(blank=True, default='', max_length=512, verbose_name='Nom du fichier')),
                ('content_type', models.CharField(default='application/pdf', max_length=128, verbose_name='Type MIME')),
                ('document_type', models.CharField(
                    default='sign',
                    help_text='sign = à signer, attachment = pièce jointe',
                    max_length=32,
                    verbose_name='Type de document',
                )),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Taille du fichier (octets)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('resource', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='document_traces',
                    to='passerelle_goodflag.goodflagresource',
                    verbose_name='Connecteur',
                )),
            ],
            options={
                'verbose_name': 'Trace document Goodflag',
                'verbose_name_plural': 'Traces document Goodflag',
                'indexes': [models.Index(fields=['resource', 'goodflag_workflow_id'], name='gf_doc_resource_wfid_idx')],
            },
        ),
    ]
